import type { AccommodationProvider, AccommodationSearchParams, AccommodationResult } from './types'

// ─── 도시별 mock 숙박 데이터 ────────────────────────────────────────────────

const MOCK_ACCOMMODATIONS: Record<string, AccommodationResult[]> = {

  // ── 서울 ──────────────────────────────────────────────────────────────────
  seoul: [
    {
      id: 'mock-hotel-seoul-1',
      name: '롯데호텔 서울',
      type: 'hotel',
      source: 'hotel',
      location: '서울 중구 을지로',
      checkIn: '',
      checkOut: '',
      pricePerNight: 250000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.7,
      reviewCount: 3841,
      amenities: ['무료 Wi-Fi', '조식 포함', '수영장', '피트니스', '스파'],
      bookingUrl: 'https://www.booking.com/hotel/kr/lotte-seoul.ko.html',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-hotel-seoul-2',
      name: '명동 게스트하우스 & 호텔',
      type: 'hotel',
      source: 'hotel',
      location: '서울 명동',
      checkIn: '',
      checkOut: '',
      pricePerNight: 90000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.3,
      reviewCount: 1520,
      amenities: ['무료 Wi-Fi', '명동 쇼핑가 도보 5분', '조식 옵션', '공항버스 인근'],
      bookingUrl: 'https://www.agoda.com/search?city=seoul&neighborhood=myeongdong',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-hotel-seoul-3',
      name: '홍대 트렌디 호텔',
      type: 'hotel',
      source: 'hotel',
      location: '서울 마포구 홍대',
      checkIn: '',
      checkOut: '',
      pricePerNight: 115000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.4,
      reviewCount: 892,
      amenities: ['무료 Wi-Fi', '24시 편의점', '홍대 클럽거리 인근', '로비 카페'],
      bookingUrl: 'https://www.booking.com/searchresults.html?ss=%ED%99%8D%EB%8C%80+%ED%98%B8%ED%85%94',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-airbnb-seoul-1',
      name: '경복궁 뷰 한옥 스테이',
      type: 'airbnb',
      source: 'airbnb',
      location: '서울 종로구 북촌',
      checkIn: '',
      checkOut: '',
      pricePerNight: 180000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.9,
      reviewCount: 284,
      amenities: ['전통 한옥', '경복궁 도보 10분', '독립 마당', '무료 Wi-Fi'],
      bookingUrl: 'https://www.airbnb.co.kr/s/Seoul--South-Korea/homes?amenities%5B%5D=hanok',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-airbnb-seoul-2',
      name: '강남 코엑스 인근 아파트',
      type: 'airbnb',
      source: 'airbnb',
      location: '서울 강남구',
      checkIn: '',
      checkOut: '',
      pricePerNight: 130000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.6,
      reviewCount: 156,
      amenities: ['풀옵션 주방', '세탁기', '코엑스 도보 7분', '무료 Wi-Fi'],
      bookingUrl: 'https://www.airbnb.co.kr/s/Gangnam--Seoul--South-Korea/homes',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-airbnb-seoul-3',
      name: '성수동 힙한 스튜디오',
      type: 'airbnb',
      source: 'airbnb',
      location: '서울 성동구 성수동',
      checkIn: '',
      checkOut: '',
      pricePerNight: 95000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.8,
      reviewCount: 97,
      amenities: ['인더스트리얼 인테리어', '카페 밀집 구역', '한강 자전거 도로 인근', '무료 Wi-Fi'],
      bookingUrl: 'https://www.airbnb.co.kr/s/Seongsu-dong--Seoul/homes',
      available: true,
      dataSource: 'mock',
    },
  ],

  // ── 제주 ──────────────────────────────────────────────────────────────────
  jeju: [
    {
      id: 'mock-hotel-jeju-1',
      name: '제주 신라 호텔',
      type: 'hotel',
      source: 'hotel',
      location: '제주시 중문관광단지',
      checkIn: '',
      checkOut: '',
      pricePerNight: 320000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.8,
      reviewCount: 2103,
      amenities: ['오션뷰', '야외 수영장', '조식 포함', '스파', '골프장 인근'],
      bookingUrl: 'https://www.shilla.net/jejuhotel/',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-hotel-jeju-2',
      name: '제주 한림 비치 호텔',
      type: 'hotel',
      source: 'hotel',
      location: '제주 한림읍 협재 해변',
      checkIn: '',
      checkOut: '',
      pricePerNight: 145000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.4,
      reviewCount: 741,
      amenities: ['해변 도보 3분', '오션뷰 객실', '무료 Wi-Fi', '자전거 대여'],
      bookingUrl: 'https://www.booking.com/searchresults.html?ss=%ED%98%91%EC%9E%AC+%ED%95%B4%EB%B3%80+%ED%98%B8%ED%85%94',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-hotel-jeju-3',
      name: '제주시 비즈니스 호텔',
      type: 'hotel',
      source: 'hotel',
      location: '제주시 연동',
      checkIn: '',
      checkOut: '',
      pricePerNight: 75000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.1,
      reviewCount: 498,
      amenities: ['무료 Wi-Fi', '공항 15분', '조식 옵션', '주차 무료'],
      bookingUrl: 'https://www.agoda.com/search?city=jeju',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-airbnb-jeju-1',
      name: '성산 일출봉 뷰 독채 펜션',
      type: 'airbnb',
      source: 'airbnb',
      location: '제주 서귀포시 성산읍',
      checkIn: '',
      checkOut: '',
      pricePerNight: 220000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.9,
      reviewCount: 173,
      amenities: ['독채 전세', '일출봉 뷰', '바비큐 시설', '무료 Wi-Fi'],
      bookingUrl: 'https://www.airbnb.co.kr/s/Seongsan--Jeju-Island/homes',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-airbnb-jeju-2',
      name: '애월 감성 카페형 게스트하우스',
      type: 'airbnb',
      source: 'airbnb',
      location: '제주 제주시 애월읍',
      checkIn: '',
      checkOut: '',
      pricePerNight: 98000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.7,
      reviewCount: 211,
      amenities: ['오션뷰 테라스', '자체 카페', '제주 귤 정원', '무료 Wi-Fi'],
      bookingUrl: 'https://www.airbnb.co.kr/s/Aewol--Jeju-Island/homes',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-airbnb-jeju-3',
      name: '한라산 뷰 제주 돌집',
      type: 'airbnb',
      source: 'airbnb',
      location: '제주 서귀포시',
      checkIn: '',
      checkOut: '',
      pricePerNight: 160000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.8,
      reviewCount: 89,
      amenities: ['전통 현무암 돌집', '한라산 뷰', '독채', '무료 Wi-Fi'],
      bookingUrl: 'https://www.airbnb.co.kr/s/Seogwipo--Jeju-Island/homes',
      available: true,
      dataSource: 'mock',
    },
  ],

  // ── 부산 ──────────────────────────────────────────────────────────────────
  busan: [
    {
      id: 'mock-hotel-busan-1',
      name: '해운대 그랜드 호텔',
      type: 'hotel',
      source: 'hotel',
      location: '부산 해운대구',
      checkIn: '',
      checkOut: '',
      pricePerNight: 200000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.6,
      reviewCount: 1832,
      amenities: ['해운대 해변 도보 3분', '오션뷰', '조식 포함', '수영장'],
      bookingUrl: 'https://www.booking.com/searchresults.html?ss=%ED%95%B4%EC%9A%B4%EB%8C%80+%ED%98%B8%ED%85%94',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-hotel-busan-2',
      name: '광안리 비치 모텔',
      type: 'hotel',
      source: 'hotel',
      location: '부산 수영구 광안리',
      checkIn: '',
      checkOut: '',
      pricePerNight: 85000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.2,
      reviewCount: 613,
      amenities: ['광안대교 야경뷰', '해변 도보 5분', '무료 주차', '무료 Wi-Fi'],
      bookingUrl: 'https://www.agoda.com/search?city=busan',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-airbnb-busan-1',
      name: '감천문화마을 아트 스테이',
      type: 'airbnb',
      source: 'airbnb',
      location: '부산 사하구 감천동',
      checkIn: '',
      checkOut: '',
      pricePerNight: 110000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.8,
      reviewCount: 142,
      amenities: ['알록달록 마을뷰', '아트 인테리어', '도보 관광 최적', '무료 Wi-Fi'],
      bookingUrl: 'https://www.airbnb.co.kr/s/Gamcheon-Culture-Village--Busan/homes',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-airbnb-busan-2',
      name: '해운대 오션프론트 아파트',
      type: 'airbnb',
      source: 'airbnb',
      location: '부산 해운대구',
      checkIn: '',
      checkOut: '',
      pricePerNight: 175000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.7,
      reviewCount: 98,
      amenities: ['풀오션뷰', '풀옵션 주방', '세탁기', '무료 Wi-Fi'],
      bookingUrl: 'https://www.airbnb.co.kr/s/Haeundae--Busan--South-Korea/homes',
      available: true,
      dataSource: 'mock',
    },
  ],

  // ── 도쿄 ──────────────────────────────────────────────────────────────────
  tokyo: [
    {
      id: 'mock-hotel-tokyo-1',
      name: '신주쿠 그랜드 호텔',
      type: 'hotel',
      source: 'hotel',
      location: '도쿄 신주쿠',
      checkIn: '',
      checkOut: '',
      pricePerNight: 120000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.3,
      reviewCount: 1284,
      amenities: ['무료 Wi-Fi', '조식 포함', '피트니스', '24시 프런트'],
      bookingUrl: 'https://www.booking.com/searchresults.html?ss=shinjuku+hotel+tokyo',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-hotel-tokyo-2',
      name: '아사쿠사 부티크 호텔',
      type: 'hotel',
      source: 'hotel',
      location: '도쿄 아사쿠사',
      checkIn: '',
      checkOut: '',
      pricePerNight: 95000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.5,
      reviewCount: 876,
      amenities: ['무료 Wi-Fi', '전통 욕실', '관광지 인근'],
      bookingUrl: 'https://www.booking.com/searchresults.html?ss=asakusa+hotel+tokyo',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-hotel-tokyo-3',
      name: '시부야 코스모스 호텔',
      type: 'hotel',
      source: 'hotel',
      location: '도쿄 시부야',
      checkIn: '',
      checkOut: '',
      pricePerNight: 140000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.1,
      reviewCount: 632,
      amenities: ['무료 Wi-Fi', '루프탑 바', '조식 옵션', '쇼핑몰 인근'],
      bookingUrl: 'https://www.agoda.com/search?city=tokyo',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-airbnb-tokyo-1',
      name: '도쿄 타워뷰 아파트먼트',
      type: 'airbnb',
      source: 'airbnb',
      location: '도쿄 미나토구',
      checkIn: '',
      checkOut: '',
      pricePerNight: 85000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.8,
      reviewCount: 312,
      amenities: ['독립 주방', '도쿄 타워 뷰', '세탁기', '무료 Wi-Fi'],
      bookingUrl: 'https://www.airbnb.co.kr/s/Tokyo--Japan/homes',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-airbnb-tokyo-2',
      name: '시모키타자와 아늑한 원룸',
      type: 'airbnb',
      source: 'airbnb',
      location: '도쿄 시모키타자와',
      checkIn: '',
      checkOut: '',
      pricePerNight: 58000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.6,
      reviewCount: 198,
      amenities: ['독립 공간', '근처 카페 많음', '무료 Wi-Fi', '자전거 대여'],
      bookingUrl: 'https://www.airbnb.co.kr/s/Shimokitazawa--Tokyo/homes',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-airbnb-tokyo-3',
      name: '나카메구로 디자이너 스튜디오',
      type: 'airbnb',
      source: 'airbnb',
      location: '도쿄 나카메구로',
      checkIn: '',
      checkOut: '',
      pricePerNight: 110000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.9,
      reviewCount: 145,
      amenities: ['인테리어 특화', '강변 산책로 인근', '주방', '무료 Wi-Fi'],
      bookingUrl: 'https://www.airbnb.co.kr/s/Nakameguro--Tokyo/homes',
      available: true,
      dataSource: 'mock',
    },
  ],

  // ── 오사카 ────────────────────────────────────────────────────────────────
  osaka: [
    {
      id: 'mock-hotel-osaka-1',
      name: '난바 플라자 호텔',
      type: 'hotel',
      source: 'hotel',
      location: '오사카 난바',
      checkIn: '',
      checkOut: '',
      pricePerNight: 100000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.4,
      reviewCount: 1100,
      amenities: ['무료 Wi-Fi', '도톤보리 도보 5분', '조식 옵션', '24시 프런트'],
      bookingUrl: 'https://www.booking.com/searchresults.html?ss=namba+hotel+osaka',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-airbnb-osaka-1',
      name: '신세카이 뷰 아파트',
      type: 'airbnb',
      source: 'airbnb',
      location: '오사카 나니와구 신세카이',
      checkIn: '',
      checkOut: '',
      pricePerNight: 65000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.5,
      reviewCount: 210,
      amenities: ['쓰텐카쿠 도보 10분', '독립 주방', '현지 분위기', '무료 Wi-Fi'],
      bookingUrl: 'https://www.airbnb.co.kr/s/Osaka--Japan/homes',
      available: true,
      dataSource: 'mock',
    },
  ],
}

// ─── 도시명 정규화 ─────────────────────────────────────────────────────────

const CITY_KEY_MAP: Record<string, string> = {
  // 한국
  '서울': 'seoul', 'seoul': 'seoul',
  '제주': 'jeju', '제주도': 'jeju', 'jeju': 'jeju',
  '부산': 'busan', 'busan': 'busan',
  '인천': 'seoul', '수원': 'seoul', '경주': 'busan',
  // 일본
  '도쿄': 'tokyo', '도꾜': 'tokyo', 'tokyo': 'tokyo',
  '오사카': 'osaka', 'osaka': 'osaka',
  '교토': 'tokyo', 'kyoto': 'tokyo',
  '후쿠오카': 'busan', 'fukuoka': 'busan',
}

function normalizeCity(destination: string): string {
  // "서울, 한국" / "서울 강남" 등 첫 단어만 추출
  const first = destination.toLowerCase().trim().split(/[\s,]+/)[0]
  return CITY_KEY_MAP[first] ?? CITY_KEY_MAP[destination.toLowerCase().trim()] ?? 'seoul'
}

function calcTotalPrice(pricePerNight: number, checkIn: string, checkOut: string): number {
  if (!checkIn || !checkOut) return pricePerNight
  const nights = Math.max(
    1,
    Math.round((new Date(checkOut).getTime() - new Date(checkIn).getTime()) / 86_400_000)
  )
  return pricePerNight * nights
}

export const mockAccommodationProvider: AccommodationProvider = {
  name: 'mock',
  async search(params: AccommodationSearchParams): Promise<AccommodationResult[]> {
    const key = normalizeCity(params.destination)
    // 매칭되는 도시 데이터 우선, 없으면 seoul fallback
    const base = MOCK_ACCOMMODATIONS[key] ?? MOCK_ACCOMMODATIONS['seoul']

    return base
      .filter((r) => {
        if (params.type === 'hotel') return r.source === 'hotel'
        if (params.type === 'airbnb') return r.source === 'airbnb'
        return true // 'all'
      })
      .map((r) => ({
        ...r,
        location: r.location, // 원본 location 그대로 유지
        checkIn: params.checkIn,
        checkOut: params.checkOut,
        totalPrice: calcTotalPrice(r.pricePerNight, params.checkIn, params.checkOut),
      }))
  },
}
