import type { ActivityProvider, ActivitySearchParams, ActivityResult } from './types'

// ─── 도시별 mock 액티비티 데이터 ──────────────────────────────────────────────

const MOCK_ACTIVITIES: Record<string, ActivityResult[]> = {

  // ── 서울 ──────────────────────────────────────────────────────────────────
  seoul: [
    {
      id: 'mock-act-seoul-1',
      name: '경복궁 & 북촌 한옥마을 가이드 투어',
      category: 'tour',
      description: '조선시대 정궁 경복궁과 북촌 한옥마을을 함께 탐방. 한복 대여 포함, 역사 해설 포함.',
      location: '서울 종로구 경복궁',
      duration: '3시간',
      pricePerPerson: 35000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.8,
      reviewCount: 2304,
      highlights: ['한복 대여 포함', '한국어·영어 가이드', '입장료 포함', '사진 촬영 명소 안내'],
      bookingUrl: 'https://www.klook.com/activity/seoul-gyeongbokgung-bukchon/',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-seoul-2',
      name: '홍대 K-뷰티 메이크업 클래스',
      category: 'experience',
      description: '한국 뷰티 전문가에게 배우는 K-뷰티 메이크업. BB크림·아이라이너·립 트렌드 실습.',
      location: '서울 홍대 뷰티 스튜디오',
      duration: '2시간',
      pricePerPerson: 55000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.7,
      reviewCount: 618,
      highlights: ['뷰티 제품 제공', '소규모 (최대 6인)', '사전 예약 필수', '한국어·영어 가능'],
      bookingUrl: 'https://www.airbnb.co.kr/experiences/seoul-kbeauty',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-seoul-3',
      name: '명동 야시장 & 한식 먹방 투어',
      category: 'food',
      description: '명동 거리 음식부터 광장시장 육회·빈대떡까지. 서울 대표 길거리 음식 10가지 시식 투어.',
      location: '서울 명동·광장시장',
      duration: '3시간',
      pricePerPerson: 45000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.9,
      reviewCount: 1052,
      highlights: ['10가지 음식 시식 포함', '현지 맛집 비밀 루트', '가이드 동행', '교통비 포함'],
      bookingUrl: 'https://www.viator.com/Seoul/d973-ttd/food-tours',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-seoul-4',
      name: '남산 & 한강 야경 투어',
      category: 'tour',
      description: 'N서울타워에서 서울 전경 감상 후 한강 유람선 탑승. 야간 서울의 아름다움을 만끽.',
      location: '서울 남산·한강',
      duration: '4시간',
      pricePerPerson: 60000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.6,
      reviewCount: 847,
      highlights: ['N서울타워 입장권 포함', '한강 유람선 탑승', '야경 포토스팟', '왕복 픽업 포함'],
      bookingUrl: 'https://www.klook.com/activity/seoul-namsan-night/',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-seoul-5',
      name: '서울 전통 도자기 클래스',
      category: 'experience',
      description: '청자·백자 전통 기법을 현대 도예 스튜디오에서 배우는 체험. 완성품 소포 발송 가능.',
      location: '서울 인사동',
      duration: '2시간',
      pricePerPerson: 48000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.7,
      reviewCount: 283,
      highlights: ['재료비 포함', '작품 소포 배송 옵션', '소규모 (최대 8인)', '한국어·영어 가능'],
      bookingUrl: 'https://www.airbnb.co.kr/experiences/seoul-ceramics',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-seoul-6',
      name: '인왕산 도성 하이킹',
      category: 'outdoor',
      description: '서울 도심 속 산행. 조선시대 한양 도성 성곽길을 따라 인왕산 정상(338m)까지 트레킹.',
      location: '서울 종로구 인왕산',
      duration: '3시간',
      pricePerPerson: 25000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.5,
      reviewCount: 412,
      highlights: ['가이드 포함', '서울 파노라마 뷰', '도성 역사 해설', '간식 제공'],
      bookingUrl: 'https://www.viator.com/Seoul/inwangsan-hike',
      available: true,
      dataSource: 'mock',
    },
  ],

  // ── 제주 ──────────────────────────────────────────────────────────────────
  jeju: [
    {
      id: 'mock-act-jeju-1',
      name: '성산 일출봉 일출 투어',
      category: 'outdoor',
      description: '유네스코 세계자연유산 성산일출봉에서 제주의 아름다운 일출 감상. 이른 아침 소규모 투어.',
      location: '제주 서귀포시 성산읍',
      duration: '3시간',
      pricePerPerson: 30000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.9,
      reviewCount: 1420,
      highlights: ['입장료 포함', '일출 최적 뷰포인트 안내', '소규모 (최대 10인)', '픽업 서비스'],
      bookingUrl: 'https://www.klook.com/activity/jeju-seongsan-sunrise/',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-jeju-2',
      name: '제주 해녀 문화 체험',
      category: 'culture',
      description: '제주 해녀 할머니에게 배우는 전통 물질 시연 관람 + 해산물 시식. 유네스코 무형문화유산.',
      location: '제주 구좌읍 해녀박물관',
      duration: '2시간',
      pricePerPerson: 40000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.8,
      reviewCount: 534,
      highlights: ['해녀 물질 시연', '신선한 해산물 시식', '문화 해설', '소규모 투어'],
      bookingUrl: 'https://www.airbnb.co.kr/experiences/jeju-haenyeo',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-jeju-3',
      name: '한라산 등반 (어리목 코스)',
      category: 'outdoor',
      description: '해발 1,950m 한라산 어리목 코스. 영실 기암과 백록담 방향 윗세오름까지 트레킹.',
      location: '제주 한라산 어리목 탐방로',
      duration: '종일 (8시간)',
      pricePerPerson: 50000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.7,
      reviewCount: 756,
      highlights: ['가이드 포함', '도시락 제공', '안전 장비 대여', '초보자 가능 코스'],
      bookingUrl: 'https://www.viator.com/Jeju/hallasan-hike',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-jeju-4',
      name: '제주 감귤 농장 체험 & 따기',
      category: 'experience',
      description: '제주 전통 감귤 농장에서 감귤 따기 체험. 가정식 감귤 잼 만들기 포함, 시식 무제한.',
      location: '제주 서귀포시 감귤 농장',
      duration: '2시간',
      pricePerPerson: 22000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.6,
      reviewCount: 921,
      highlights: ['감귤 1kg 가져가기', '잼 만들기 체험', '농장 가이드', '가족 단위 추천'],
      bookingUrl: 'https://www.klook.com/activity/jeju-citrus-farm/',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-jeju-5',
      name: '제주 협재 해변 서핑 레슨',
      category: 'outdoor',
      description: '에메랄드빛 협재 해변에서 즐기는 초보자 서핑 레슨. 강사 1:4 비율, 장비 포함.',
      location: '제주 한림읍 협재 해변',
      duration: '2시간',
      pricePerPerson: 70000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.7,
      reviewCount: 389,
      highlights: ['서핑 장비 포함', '초보자 전용 코스', '사진 촬영 서비스', '샤워 시설'],
      bookingUrl: 'https://www.airbnb.co.kr/experiences/jeju-surfing',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-jeju-6',
      name: '제주 전통 흑돼지 BBQ 쿠킹 클래스',
      category: 'food',
      description: '제주 흑돼지 부위별 특성 설명 + 전통 방식 BBQ 조리 실습. 된장찌개·쌈 채소 포함 한상 차리기.',
      location: '제주 서귀포시',
      duration: '2.5시간',
      pricePerPerson: 65000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.9,
      reviewCount: 217,
      highlights: ['흑돼지 1인분 포함', '쌈 채소·된장찌개', '소규모 (최대 8인)', '레시피 제공'],
      bookingUrl: 'https://www.airbnb.co.kr/experiences/jeju-blackpork-bbq',
      available: true,
      dataSource: 'mock',
    },
  ],

  // ── 부산 ──────────────────────────────────────────────────────────────────
  busan: [
    {
      id: 'mock-act-busan-1',
      name: '감천문화마을 아트 투어',
      category: 'culture',
      description: '한국의 산토리니 감천문화마을. 알록달록 골목길 예술 작품과 숨겨진 뷰포인트 투어.',
      location: '부산 사하구 감천동',
      duration: '2시간',
      pricePerPerson: 20000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.7,
      reviewCount: 1830,
      highlights: ['아트 작품 해설', '포토스팟 안내', '현지 카페 할인', '소규모 (최대 10인)'],
      bookingUrl: 'https://www.klook.com/activity/busan-gamcheon/',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-busan-2',
      name: '해운대 & 광안리 야경 크루즈',
      category: 'tour',
      description: '해운대와 광안대교를 바다에서 바라보는 야간 크루즈. 음료 1잔 포함, 야경 포토타임.',
      location: '부산 해운대 해수욕장 선착장',
      duration: '1.5시간',
      pricePerPerson: 38000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.6,
      reviewCount: 724,
      highlights: ['음료 1잔 포함', '광안대교 야경', '야간 사진 촬영 포인트', '커플 추천'],
      bookingUrl: 'https://www.viator.com/Busan/night-cruise',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-busan-3',
      name: '부산 자갈치 시장 해산물 투어',
      category: 'food',
      description: '한국 최대 수산물 시장 자갈치에서 싱싱한 회·조개구이 시식. 식당 예약 없이 즐기는 현지 먹방.',
      location: '부산 중구 자갈치 시장',
      duration: '3시간',
      pricePerPerson: 55000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.8,
      reviewCount: 592,
      highlights: ['회·조개구이 시식 포함', '시장 투어', '현지 맛집 비밀 가이드', '소규모'],
      bookingUrl: 'https://www.airbnb.co.kr/experiences/busan-jagalchi',
      available: true,
      dataSource: 'mock',
    },
  ],

  // ── 도쿄 ──────────────────────────────────────────────────────────────────
  tokyo: [
    {
      id: 'mock-act-tokyo-1',
      name: '도쿄 스시 만들기 쿠킹 클래스',
      category: 'experience',
      description: '현지 셰프에게 직접 배우는 정통 스시 & 사시미 만들기. 식재료 선택부터 플레이팅까지 2시간 코스.',
      location: '도쿄 긴자',
      duration: '2시간',
      pricePerPerson: 65000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.8,
      reviewCount: 523,
      highlights: ['영어·한국어 안내 가능', '식재료 포함', '레시피 카드 제공', '최대 8인 소규모'],
      bookingUrl: 'https://www.viator.com/Tokyo/d334-ttd',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-tokyo-2',
      name: '아사쿠사 & 도쿄 스카이트리 반일 투어',
      category: 'tour',
      description: '도쿄의 과거와 현재를 동시에. 전통 사찰 센소지와 634m 스카이트리를 함께 즐기는 반일 가이드 투어.',
      location: '도쿄 아사쿠사',
      duration: '4시간',
      pricePerPerson: 45000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.6,
      reviewCount: 1204,
      highlights: ['한국어 가이드', '입장료 포함', '소규모 그룹 (최대 12인)', '점심 옵션 추가 가능'],
      bookingUrl: 'https://www.klook.com/activity/tokyo-asakusa-skytree/',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-tokyo-3',
      name: '하라주쿠 스트리트 푸드 투어',
      category: 'food',
      description: '다케시타 거리부터 오모테산도까지 도쿄 팝 컬처와 먹거리를 동시에 탐방. 8가지 시식.',
      location: '도쿄 하라주쿠',
      duration: '3시간',
      pricePerPerson: 55000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.7,
      reviewCount: 318,
      highlights: ['8가지 시식 포함', '가이드 동행', '인스타그램 포토스팟 안내', '그룹 최대 10인'],
      bookingUrl: 'https://www.airbnb.co.kr/experiences/tokyo',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-tokyo-4',
      name: '후지산 당일치기 버스 투어',
      category: 'outdoor',
      description: '도쿄 출발 후지산 5합목 + 가와구치코 호수 코스. 전망대에서 후지산 절경 감상.',
      location: '도쿄 → 후지산',
      duration: '종일 (12시간)',
      pricePerPerson: 95000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.5,
      reviewCount: 2187,
      highlights: ['왕복 교통 포함', '한국어 오디오 가이드', '점심 식사 포함', '우천 환불 정책'],
      bookingUrl: 'https://www.klook.com/activity/tokyo-fuji-day-trip/',
      available: true,
      dataSource: 'mock',
    },
  ],

  // ── 오키나와 ────────────────────────────────────────────────────────────────
  okinawa: [
    {
      id: 'mock-act-okinawa-1',
      name: '케라마 제도 스노클링 투어',
      category: 'outdoor',
      description: '오키나와 본섬에서 배로 30분, 세계 최고 수준의 산호초를 자랑하는 케라마 제도 스노클링. 투명한 에메랄드 바다에서 형형색색 열대어와 만남.',
      location: '오키나와 나하 도마리항 출발',
      duration: '6시간',
      pricePerPerson: 85000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.9,
      reviewCount: 1842,
      highlights: ['스노클링 장비 포함', '한국어 가이드', '점심 도시락 제공', '수영 초보 가능'],
      bookingUrl: 'https://www.klook.com/activity/kerama-islands-snorkeling-okinawa/',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-okinawa-2',
      name: '슈리성 & 나하 국제거리 역사 투어',
      category: 'culture',
      description: '유네스코 세계유산 슈리성과 류큐 왕국의 역사를 탐방. 국제거리 시장 투어 및 오키나와 전통 소품 쇼핑 가이드 포함.',
      location: '오키나와 나하시 슈리',
      duration: '4시간',
      pricePerPerson: 38000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.6,
      reviewCount: 983,
      highlights: ['슈리성 입장권 포함', '한국어 가이드', '국제거리 자유시간', '전통 공예품 쇼핑 안내'],
      bookingUrl: 'https://www.viator.com/Okinawa/d4726-ttd/tours',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-okinawa-3',
      name: '오키나와 전통 류큐 요리 클래스',
      category: 'experience',
      description: '오키나와 전통 장수 식재료로 만드는 류큐 요리 체험. 찬푸루·라프테·두부요리 등 건강식 3종 조리 실습.',
      location: '오키나와 나하시',
      duration: '2.5시간',
      pricePerPerson: 60000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.8,
      reviewCount: 347,
      highlights: ['식재료 포함', '레시피 한국어 번역본 제공', '소규모 (최대 8인)', '아와모리 시음 옵션'],
      bookingUrl: 'https://www.airbnb.co.kr/experiences/1234567',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-okinawa-4',
      name: '만자모 · 온나손 드라이브 투어',
      category: 'tour',
      description: '오키나와 중부 절경 드라이브. 코끼리 바위 만자모, 온나손 비치, 아메리칸 빌리지까지 소규모 밴 투어.',
      location: '오키나와 온나손 · 차탄',
      duration: '5시간',
      pricePerPerson: 55000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.7,
      reviewCount: 612,
      highlights: ['한국어 드라이버 가이드', '만자모·아메리칸빌리지 포함', '소규모 (최대 6인)', '픽업 서비스'],
      bookingUrl: 'https://www.klook.com/activity/okinawa-manzamo-onnason-tour/',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-okinawa-5',
      name: '오키나와 소바 & 먹거리 투어',
      category: 'food',
      description: '오키나와 소바, 사타안다기(도넛), 아구 돼지고기 등 현지 먹거리를 국제거리와 마키시 시장에서 탐방.',
      location: '오키나와 나하 마키시 공설시장',
      duration: '3시간',
      pricePerPerson: 45000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.7,
      reviewCount: 498,
      highlights: ['오키나와 소바 포함', '6가지 시식', '마키시 시장 가이드', '소규모'],
      bookingUrl: 'https://www.viator.com/Okinawa/d4726-ttd/food-tours',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-okinawa-6',
      name: '오키나와 서핑 레슨 (온나손)',
      category: 'outdoor',
      description: '맑은 에메랄드 바다에서 즐기는 초보자용 서핑 레슨. 장비 포함, 강사 1:4 비율, 기초 수영 가능이면 참여 가능.',
      location: '오키나와 온나손 비치',
      duration: '2시간',
      pricePerPerson: 72000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.6,
      reviewCount: 253,
      highlights: ['서핑 장비 포함', '초보자 전용', '샤워 시설', '사진 촬영 서비스'],
      bookingUrl: 'https://www.klook.com/activity/okinawa-surfing-lesson/',
      available: true,
      dataSource: 'mock',
    },
  ],

  // ── 오사카 ────────────────────────────────────────────────────────────────
  osaka: [
    {
      id: 'mock-act-osaka-1',
      name: '오사카 타코야키 만들기 체험',
      category: 'experience',
      description: '오사카 소울푸드 타코야키를 현지 장인에게 직접 배우는 클래스. 재료 포함, 무제한 시식.',
      location: '오사카 난바',
      duration: '1.5시간',
      pricePerPerson: 35000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.8,
      reviewCount: 891,
      highlights: ['타코야키 재료 포함', '무제한 시식', '한국어 안내 가능', '소규모 (최대 8인)'],
      bookingUrl: 'https://www.viator.com/Osaka/takoyaki-class',
      available: true,
      dataSource: 'mock',
    },
    {
      id: 'mock-act-osaka-2',
      name: '도톤보리 야식 투어',
      category: 'food',
      description: '오사카 최대 번화가 도톤보리의 야식 명소를 현지 가이드와 탐방. 쿠시카츠·오코노미야키 포함.',
      location: '오사카 도톤보리',
      duration: '2.5시간',
      pricePerPerson: 50000,
      currency: 'KRW',
      totalPrice: 0,
      rating: 4.7,
      reviewCount: 643,
      highlights: ['음식 5가지 포함', '야간 네온사인 포토', '현지 비밀 맛집', '소규모'],
      bookingUrl: 'https://www.klook.com/activity/osaka-dotonbori-food/',
      available: true,
      dataSource: 'mock',
    },
  ],
}

// ─── 도시명 정규화 ─────────────────────────────────────────────────────────

const CITY_KEY_MAP: Record<string, string> = {
  // 한국
  '서울': 'seoul', 'seoul': 'seoul',
  '제주': 'jeju', '제주도': 'jeju', 'jeju': 'jeju',
  '부산': 'busan', 'busan': 'busan',
  '인천': 'seoul', '수원': 'seoul', '경주': 'busan',
  // 일본
  '도쿄': 'tokyo', '도꾜': 'tokyo', 'tokyo': 'tokyo',
  '오사카': 'osaka', 'osaka': 'osaka',
  '교토': 'tokyo', 'kyoto': 'tokyo',
  '후쿠오카': 'fukuoka', 'fukuoka': 'fukuoka',
  // 오키나와 (IATA: OKA) — 이전에 누락되어 서울 fallback되던 버그 수정
  '오키나와': 'okinawa', 'okinawa': 'okinawa', 'oka': 'okinawa',
  '나하': 'okinawa', 'naha': 'okinawa',
  '미야코지마': 'okinawa', '이시가키': 'okinawa',
}

/**
 * 도시명을 정규화해 MOCK_ACTIVITIES 키로 반환한다.
 * 매핑되지 않은 도시는 null → 빈 배열 반환 (서울 fallback 금지).
 */
function normalizeCity(destination: string): string | null {
  const first = destination.toLowerCase().trim().split(/[\s,]+/)[0]
  return CITY_KEY_MAP[first] ?? CITY_KEY_MAP[destination.toLowerCase().trim()] ?? null
}

function calcTotalPrice(pricePerPerson: number, guests: number): number {
  return pricePerPerson * Math.max(1, guests)
}

export const mockActivityProvider: ActivityProvider = {
  name: 'mock',
  async search(params: ActivitySearchParams): Promise<ActivityResult[]> {
    const key = normalizeCity(params.destination)
    // 매핑되지 않은 도시는 빈 배열 반환 (엉뚱한 도시 데이터 표시 방지)
    const base = key ? (MOCK_ACTIVITIES[key] ?? []) : []

    return base
      .filter((a) => {
        if (params.category && params.category !== 'all') return a.category === params.category
        if (params.maxPrice && a.pricePerPerson > params.maxPrice) return false
        return true
      })
      .map((a) => ({
        ...a,
        date: params.date ?? '',
        totalPrice: calcTotalPrice(a.pricePerPerson, params.guests ?? 2),
      }))
  },
}
