import type { RentalCarResult, RentalCarSearchParams } from './types'

// 도시 정규화 (숙박/액티비티 패턴 동일)
function normalizeCity(destination: string): string | null {
  const d = destination.toLowerCase()
  if (d.includes('오키나와') || d.includes('나하') || d.includes('oka') || d.includes('okinawa')) return 'okinawa'
  if (d.includes('도쿄') || d.includes('tokyo') || d.includes('nrt') || d.includes('hnd')) return 'tokyo'
  if (d.includes('오사카') || d.includes('osaka') || d.includes('kix')) return 'osaka'
  if (d.includes('교토') || d.includes('kyoto')) return 'kyoto'
  if (d.includes('후쿠오카') || d.includes('fukuoka') || d.includes('fuk')) return 'fukuoka'
  if (d.includes('삿포로') || d.includes('sapporo') || d.includes('cts')) return 'sapporo'
  if (d.includes('방콕') || d.includes('bangkok') || d.includes('bkk')) return 'bangkok'
  if (d.includes('싱가포르') || d.includes('singapore') || d.includes('sin')) return 'singapore'
  if (d.includes('발리') || d.includes('bali') || d.includes('dps')) return 'bali'
  if (d.includes('제주') || d.includes('jeju') || d.includes('cju')) return 'jeju'
  return null
}

const BASE_CARS: Record<string, RentalCarResult[]> = {
  okinawa: [
    {
      id: 'oki-times-aqua',
      vendor: 'Times Car',
      vendorLogoText: 'TC',
      carName: 'Toyota Aqua (하이브리드)',
      category: 'compact',
      transmission: 'auto',
      seats: 5,
      pricePerDay: 35000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: '나하 공항',
      features: ['GPS 포함', '보험 포함', '소형·연비 우수'],
      bookingUrl: 'https://rental.timescar.jp/',
      rating: 4.5,
      reviewCount: 312,
    },
    {
      id: 'oki-orix-fit',
      vendor: 'Orix Rent-a-Car',
      vendorLogoText: 'OR',
      carName: 'Honda Fit',
      category: 'compact',
      transmission: 'auto',
      seats: 5,
      pricePerDay: 30000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: '나하 공항',
      features: ['GPS 포함', '기본 보험', '저렴한 가격'],
      bookingUrl: 'https://car.orix.co.jp/',
      rating: 4.3,
      reviewCount: 186,
    },
    {
      id: 'oki-budget-freed',
      vendor: 'Budget Rent-a-Car',
      vendorLogoText: 'BG',
      carName: 'Honda Freed',
      category: 'minivan',
      transmission: 'auto',
      seats: 6,
      pricePerDay: 52000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: '나하 공항',
      features: ['GPS 포함', '보험 포함', '6인 탑승', 'ETC 카드'],
      bookingUrl: 'https://www.budgetjapan.jp/',
      rating: 4.1,
      reviewCount: 94,
    },
    {
      id: 'oki-nippon-suv',
      vendor: 'Nippon Rent-a-Car',
      vendorLogoText: 'NR',
      carName: 'Toyota RAV4',
      category: 'suv',
      transmission: 'auto',
      seats: 5,
      pricePerDay: 68000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: '나하 공항',
      features: ['GPS 포함', '완전 보험', '오키나와 드라이브 최적화', 'ETC 카드'],
      bookingUrl: 'https://www.nipponrentacar.co.jp/',
      rating: 4.6,
      reviewCount: 147,
    },
  ],
  tokyo: [
    {
      id: 'tky-times-prius',
      vendor: 'Times Car',
      vendorLogoText: 'TC',
      carName: 'Toyota Prius (하이브리드)',
      category: 'sedan',
      transmission: 'auto',
      seats: 5,
      pricePerDay: 45000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: '신주쿠 영업소',
      features: ['GPS 포함', '기본 보험', '연비 우수'],
      bookingUrl: 'https://rental.timescar.jp/',
      rating: 4.4,
      reviewCount: 503,
    },
    {
      id: 'tky-nippon-noah',
      vendor: 'Nippon Rent-a-Car',
      vendorLogoText: 'NR',
      carName: 'Toyota Noah',
      category: 'minivan',
      transmission: 'auto',
      seats: 7,
      pricePerDay: 78000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: '나리타 공항',
      features: ['GPS 포함', '완전 보험', '7인 탑승', 'ETC 카드'],
      bookingUrl: 'https://www.nipponrentacar.co.jp/',
      rating: 4.5,
      reviewCount: 228,
    },
    {
      id: 'tky-toyota-lexus',
      vendor: 'Toyota Rent-a-Car',
      vendorLogoText: 'TY',
      carName: 'Lexus ES (럭셔리)',
      category: 'luxury',
      transmission: 'auto',
      seats: 5,
      pricePerDay: 145000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: '하네다 공항',
      features: ['GPS 포함', '완전 보험', '프리미엄 서비스', 'ETC 카드'],
      bookingUrl: 'https://rent.toyota.co.jp/',
      rating: 4.8,
      reviewCount: 67,
    },
  ],
  osaka: [
    {
      id: 'osa-eki-march',
      vendor: 'Ekimae Rent-a-Car',
      vendorLogoText: 'EK',
      carName: 'Nissan March',
      category: 'compact',
      transmission: 'auto',
      seats: 5,
      pricePerDay: 28000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: '간사이 공항',
      features: ['GPS 포함', '기본 보험', '소형'],
      bookingUrl: 'https://www.ekimae-rent.jp/',
      rating: 4.2,
      reviewCount: 149,
    },
    {
      id: 'osa-orix-voxy',
      vendor: 'Orix Rent-a-Car',
      vendorLogoText: 'OR',
      carName: 'Toyota Voxy',
      category: 'minivan',
      transmission: 'auto',
      seats: 7,
      pricePerDay: 72000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: '간사이 공항',
      features: ['GPS 포함', '완전 보험', '7인 탑승'],
      bookingUrl: 'https://car.orix.co.jp/',
      rating: 4.3,
      reviewCount: 87,
    },
  ],
  bali: [
    {
      id: 'bli-avis-avanza',
      vendor: 'Avis',
      vendorLogoText: 'AV',
      carName: 'Toyota Avanza',
      category: 'suv',
      transmission: 'manual',
      seats: 7,
      pricePerDay: 25000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: '응우라라이 공항',
      features: ['기사 포함 옵션', '기본 보험'],
      bookingUrl: 'https://www.avis.com/',
      rating: 4.0,
      reviewCount: 234,
    },
    {
      id: 'bli-hertz-xpander',
      vendor: 'Hertz',
      vendorLogoText: 'HZ',
      carName: 'Mitsubishi Xpander',
      category: 'suv',
      transmission: 'auto',
      seats: 7,
      pricePerDay: 38000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: '우붓 사무소',
      features: ['GPS 포함', '완전 보험', '기사 포함 옵션'],
      bookingUrl: 'https://www.hertz.com/',
      rating: 4.3,
      reviewCount: 112,
    },
  ],
  jeju: [
    {
      id: 'jeju-kt-morning',
      vendor: '제주관광렌터카',
      vendorLogoText: 'JT',
      carName: '기아 모닝',
      category: 'compact',
      transmission: 'auto',
      seats: 4,
      pricePerDay: 42000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: '제주 공항',
      features: ['보험 포함', '연비 우수', '자차 포함'],
      bookingUrl: 'https://www.jejurentcar.com/',
      rating: 4.1,
      reviewCount: 523,
    },
    {
      id: 'jeju-lotte-spark',
      vendor: '롯데렌터카',
      vendorLogoText: 'LT',
      carName: '쉐보레 스파크',
      category: 'compact',
      transmission: 'auto',
      seats: 4,
      pricePerDay: 38000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: '제주 공항',
      features: ['완전 자차 보험', '경차 혜택'],
      bookingUrl: 'https://www.lotterentacar.net/',
      rating: 4.2,
      reviewCount: 741,
    },
    {
      id: 'jeju-sk-tucson',
      vendor: 'SK 렌터카',
      vendorLogoText: 'SK',
      carName: '현대 투싼',
      category: 'suv',
      transmission: 'auto',
      seats: 5,
      pricePerDay: 78000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: '제주 공항',
      features: ['완전 보험', 'SUV', '넉넉한 트렁크'],
      bookingUrl: 'https://www.skrentcar.com/',
      rating: 4.4,
      reviewCount: 318,
    },
  ],
}

// 그 외 도시에 대한 기본 세트 (도시명만 변경)
function buildGenericSet(pickupCity: string): RentalCarResult[] {
  return [
    {
      id: `generic-compact-${pickupCity}`,
      vendor: 'Budget Rent-a-Car',
      vendorLogoText: 'BG',
      carName: '소형차 (Economy)',
      category: 'compact',
      transmission: 'auto',
      seats: 5,
      pricePerDay: 32000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: `${pickupCity} 공항`,
      features: ['GPS 포함', '기본 보험'],
      bookingUrl: 'https://www.budget.com/',
      rating: 4.0,
      reviewCount: 50,
    },
    {
      id: `generic-suv-${pickupCity}`,
      vendor: 'Hertz',
      vendorLogoText: 'HZ',
      carName: 'SUV (중형)',
      category: 'suv',
      transmission: 'auto',
      seats: 5,
      pricePerDay: 65000,
      totalPrice: 0,
      currency: 'KRW',
      pickupLocation: `${pickupCity} 공항`,
      features: ['GPS 포함', '완전 보험', '넉넉한 공간'],
      bookingUrl: 'https://www.hertz.com/',
      rating: 4.2,
      reviewCount: 30,
    },
  ]
}

function calcDays(from: string, to: string): number {
  const diff = new Date(to).getTime() - new Date(from).getTime()
  const days = Math.max(1, Math.round(diff / (1000 * 60 * 60 * 24)))
  return days
}

export function getMockRentalCars(params: RentalCarSearchParams): RentalCarResult[] {
  const city = normalizeCity(params.destination)
  const baseCars = city ? (BASE_CARS[city] ?? buildGenericSet(params.destination)) : buildGenericSet(params.destination)
  const days = calcDays(params.pickupDate, params.returnDate)

  return baseCars.map((car) => ({
    ...car,
    totalPrice: car.pricePerDay * days,
  }))
}
